### PR TITLE
Marge all valid pull reqeusts and add some new badges

### LINKED ISSUE #53: Blazor
Could you add a Blazor badge please?

https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor

### LINKED ISSUE #62: Add Badge for Github
Please add a badge for Github icon .

### PR DESCRIPTION
**Pull request by 0x61nas**
* Merged pull reqests:
  * #77 from @TheDanielDoyle, fix #53 issue
  * Merge the valid edit only from #64, @Railly
  * #59 from @Lzyct
  * #45 from @klaasnicolaas
  * Merge the valid edit only from #42, @fenix-hub

* New Badges Added:
  * GitHub badge, fix #62 issue
  * GitLab badge
  * Bitbucket badge
  * Matrix badge

> And other small improvements

### CODE REVIEW

**Comment by 0x61nas** [comment]
https://www.figma.com/file/ZLPo7RjYcKUgcenjVAflPN/badges?node-id=1%3A4180

**Comment by klaasnicolaas** [comment]
Why do you put other people's work in your own PR? After all, these are still open for review (which will probably never happen). This way is really a no go...

**Comment by 0x61nas** [comment]
@klaasnicolaas Because the `badges.fig` file cannot be merged like normal code files, but it is combined as a single block so if it merges any pull request will cause conflicts in the rest, so it must be merged manually, I took the trouble and I merged all the valid pull requests manually

**Comment by 0x61nas** [comment]
@klaasnicolaas thanks for `thumbs down`, Most likely it will not even be merged or reviwed, because it is clear that there has been no activity from the owner in this repository for a year or more so rest assured 🥲 , I will create and maintain my version, and this is the main reason why I merge pull requests because it has been open for a while and has not been merged

**Comment by klaasnicolaas** [comment]
You could also have asked first before merging everything 😉 Think you can understand that this action does not seem particularly desirable at first, for those who have previously worked on their own PR. That the figma file can cause merge conflicts is a problem that could have been foreseen from the beginning of this repository. Good luck maintaining your own fork 👍🏻

**Pull request closed without merging**
