### PR TITLE
Remove trailing space characters

### PR DESCRIPTION
**Pull request by aaronfranke**
These are pointless and do nothing, so I removed them.

If you want, I can supply a CI script to automatically check for formatting issues like this.

### CODE REVIEW

**Comment by aaronfranke** [comment]
@MikeCodesDotNET I rebased this, it's mergeable now, when you have the time.

**Review by swapnanildutta — APPROVED** [review]

**Comment by aaronfranke** [comment]
@MikeCodesDotNET Ping

**Comment by aaronfranke** [comment]
@MikeCodesDotNET Ping

**Comment by aaronfranke** [comment]
Since the owner of this repo has abandoned it, I am closing this PR.

**Pull request closed without merging**
